powerData <- readRDS("powerData.rds")
par(mfrow = c(2,2))
plot(powerData$Date_time, powerData$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(powerData$Date_time, powerData$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(powerData$Date_time, powerData$Sub_metering_1, col = "darkgrey", type = "l", xlab = "", ylab = "Energy sub metering")
lines(powerData$Date_time, powerData$Sub_metering_2, col = "red")
lines(powerData$Date_time, powerData$Sub_metering_3, col = "blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="l",col=c("black","red","blue"),lwd=2,cex=0.7)
plot(powerData$Date_time, powerData$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.copy(png, file = "plot4.png", width = 480, height = 480)
dev.off()